title: Chioma Nwawuba
logo: data.jpg
description: Turning data into decisions, one project at a time. | Data Analyst | Excel • SQL • Power BI • Python | MSc AI & Data Science | Healthcare & Business Analytics

#show_downloads: true
#goggle_analytics:
theme: jekyll-theme-minimal
