title: Chioma Nwawuba
logo: IMG_1354.jpeg
description: Turning data into decisions, one project at a time. | Data Analyst | Excel • SQL • Power BI • Python | MSc AI & Data Science | Healthcare & Business Analytics

#show_downloads: true
#goggle_analytics:
theme: jekyll-theme-minimal
